name: C/C++ Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install gtest
        run: sudo apt-get install libgtest-dev
      - name: build
        run: make test
      - name: run
        run: ./test
